//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2025 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	apisconfig "github.com/gardener/gardener/extensions/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	config "github.com/metal-stack/gardener-extension-duros-provider/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DurosPartitionConfiguration)(nil), (*config.DurosPartitionConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurosPartitionConfiguration_To_config_DurosPartitionConfiguration(a.(*DurosPartitionConfiguration), b.(*config.DurosPartitionConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DurosPartitionConfiguration)(nil), (*DurosPartitionConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DurosPartitionConfiguration_To_v1alpha1_DurosPartitionConfiguration(a.(*config.DurosPartitionConfiguration), b.(*DurosPartitionConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DurosSeedStorageClass)(nil), (*config.DurosSeedStorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurosSeedStorageClass_To_config_DurosSeedStorageClass(a.(*DurosSeedStorageClass), b.(*config.DurosSeedStorageClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DurosSeedStorageClass)(nil), (*DurosSeedStorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(a.(*config.DurosSeedStorageClass), b.(*DurosSeedStorageClass), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.PartitionConfig = *(*map[string]config.DurosPartitionConfiguration)(unsafe.Pointer(&in.PartitionConfig))
	out.HealthCheckConfig = (*apisconfig.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.PartitionConfig = *(*map[string]DurosPartitionConfiguration)(unsafe.Pointer(&in.PartitionConfig))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_DurosPartitionConfiguration_To_config_DurosPartitionConfiguration(in *DurosPartitionConfiguration, out *config.DurosPartitionConfiguration, s conversion.Scope) error {
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	out.AdminKey = in.AdminKey
	out.AdminToken = in.AdminToken
	out.StorageClasses = *(*[]config.DurosSeedStorageClass)(unsafe.Pointer(&in.StorageClasses))
	out.APIEndpoint = in.APIEndpoint
	out.APICA = in.APICA
	out.APICert = in.APICert
	out.APIKey = in.APIKey
	return nil
}

// Convert_v1alpha1_DurosPartitionConfiguration_To_config_DurosPartitionConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_DurosPartitionConfiguration_To_config_DurosPartitionConfiguration(in *DurosPartitionConfiguration, out *config.DurosPartitionConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurosPartitionConfiguration_To_config_DurosPartitionConfiguration(in, out, s)
}

func autoConvert_config_DurosPartitionConfiguration_To_v1alpha1_DurosPartitionConfiguration(in *config.DurosPartitionConfiguration, out *DurosPartitionConfiguration, s conversion.Scope) error {
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	out.AdminKey = in.AdminKey
	out.AdminToken = in.AdminToken
	out.StorageClasses = *(*[]DurosSeedStorageClass)(unsafe.Pointer(&in.StorageClasses))
	out.APIEndpoint = in.APIEndpoint
	out.APICA = in.APICA
	out.APICert = in.APICert
	out.APIKey = in.APIKey
	return nil
}

// Convert_config_DurosPartitionConfiguration_To_v1alpha1_DurosPartitionConfiguration is an autogenerated conversion function.
func Convert_config_DurosPartitionConfiguration_To_v1alpha1_DurosPartitionConfiguration(in *config.DurosPartitionConfiguration, out *DurosPartitionConfiguration, s conversion.Scope) error {
	return autoConvert_config_DurosPartitionConfiguration_To_v1alpha1_DurosPartitionConfiguration(in, out, s)
}

func autoConvert_v1alpha1_DurosSeedStorageClass_To_config_DurosSeedStorageClass(in *DurosSeedStorageClass, out *config.DurosSeedStorageClass, s conversion.Scope) error {
	out.Name = in.Name
	out.ReplicaCount = in.ReplicaCount
	out.Compression = in.Compression
	out.Encryption = in.Encryption
	return nil
}

// Convert_v1alpha1_DurosSeedStorageClass_To_config_DurosSeedStorageClass is an autogenerated conversion function.
func Convert_v1alpha1_DurosSeedStorageClass_To_config_DurosSeedStorageClass(in *DurosSeedStorageClass, out *config.DurosSeedStorageClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurosSeedStorageClass_To_config_DurosSeedStorageClass(in, out, s)
}

func autoConvert_config_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(in *config.DurosSeedStorageClass, out *DurosSeedStorageClass, s conversion.Scope) error {
	out.Name = in.Name
	out.ReplicaCount = in.ReplicaCount
	out.Compression = in.Compression
	out.Encryption = in.Encryption
	return nil
}

// Convert_config_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass is an autogenerated conversion function.
func Convert_config_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(in *config.DurosSeedStorageClass, out *DurosSeedStorageClass, s conversion.Scope) error {
	return autoConvert_config_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(in, out, s)
}
