//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2025 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	apisconfig "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	config "github.com/metal-stack/gardener-extension-duros/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DurosRegionConfiguration)(nil), (*config.DurosRegionConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurosRegionConfiguration_To_config_DurosRegionConfiguration(a.(*DurosRegionConfiguration), b.(*config.DurosRegionConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DurosRegionConfiguration)(nil), (*DurosRegionConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DurosRegionConfiguration_To_v1alpha1_DurosRegionConfiguration(a.(*config.DurosRegionConfiguration), b.(*DurosRegionConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QoSPolicy)(nil), (*config.QoSPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_QoSPolicy_To_config_QoSPolicy(a.(*QoSPolicy), b.(*config.QoSPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.QoSPolicy)(nil), (*QoSPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_QoSPolicy_To_v1alpha1_QoSPolicy(a.(*config.QoSPolicy), b.(*QoSPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReadWriteLimit)(nil), (*config.ReadWriteLimit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReadWriteLimit_To_config_ReadWriteLimit(a.(*ReadWriteLimit), b.(*config.ReadWriteLimit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ReadWriteLimit)(nil), (*ReadWriteLimit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ReadWriteLimit_To_v1alpha1_ReadWriteLimit(a.(*config.ReadWriteLimit), b.(*ReadWriteLimit), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	out.RegionConfig = *(*map[string]config.DurosRegionConfiguration)(unsafe.Pointer(&in.RegionConfig))
	out.HealthCheckConfig = (*apisconfig.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	out.RegionConfig = *(*map[string]DurosRegionConfiguration)(unsafe.Pointer(&in.RegionConfig))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_DurosRegionConfiguration_To_config_DurosRegionConfiguration(in *DurosRegionConfiguration, out *config.DurosRegionConfiguration, s conversion.Scope) error {
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	out.AdminKey = in.AdminKey
	out.AdminToken = in.AdminToken
	out.APIEndpoint = in.APIEndpoint
	out.APICA = in.APICA
	out.APICert = in.APICert
	out.APIKey = in.APIKey
	out.QoSPolicies = *(*[]config.QoSPolicy)(unsafe.Pointer(&in.QoSPolicies))
	return nil
}

// Convert_v1alpha1_DurosRegionConfiguration_To_config_DurosRegionConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_DurosRegionConfiguration_To_config_DurosRegionConfiguration(in *DurosRegionConfiguration, out *config.DurosRegionConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurosRegionConfiguration_To_config_DurosRegionConfiguration(in, out, s)
}

func autoConvert_config_DurosRegionConfiguration_To_v1alpha1_DurosRegionConfiguration(in *config.DurosRegionConfiguration, out *DurosRegionConfiguration, s conversion.Scope) error {
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	out.AdminKey = in.AdminKey
	out.AdminToken = in.AdminToken
	out.APIEndpoint = in.APIEndpoint
	out.APICA = in.APICA
	out.APICert = in.APICert
	out.APIKey = in.APIKey
	out.QoSPolicies = *(*[]QoSPolicy)(unsafe.Pointer(&in.QoSPolicies))
	return nil
}

// Convert_config_DurosRegionConfiguration_To_v1alpha1_DurosRegionConfiguration is an autogenerated conversion function.
func Convert_config_DurosRegionConfiguration_To_v1alpha1_DurosRegionConfiguration(in *config.DurosRegionConfiguration, out *DurosRegionConfiguration, s conversion.Scope) error {
	return autoConvert_config_DurosRegionConfiguration_To_v1alpha1_DurosRegionConfiguration(in, out, s)
}

func autoConvert_v1alpha1_QoSPolicy_To_config_QoSPolicy(in *QoSPolicy, out *config.QoSPolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = config.QoSType(in.Type)
	if err := Convert_v1alpha1_ReadWriteLimit_To_config_ReadWriteLimit(&in.Limit, &out.Limit, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_QoSPolicy_To_config_QoSPolicy is an autogenerated conversion function.
func Convert_v1alpha1_QoSPolicy_To_config_QoSPolicy(in *QoSPolicy, out *config.QoSPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_QoSPolicy_To_config_QoSPolicy(in, out, s)
}

func autoConvert_config_QoSPolicy_To_v1alpha1_QoSPolicy(in *config.QoSPolicy, out *QoSPolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = QoSType(in.Type)
	if err := Convert_config_ReadWriteLimit_To_v1alpha1_ReadWriteLimit(&in.Limit, &out.Limit, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_QoSPolicy_To_v1alpha1_QoSPolicy is an autogenerated conversion function.
func Convert_config_QoSPolicy_To_v1alpha1_QoSPolicy(in *config.QoSPolicy, out *QoSPolicy, s conversion.Scope) error {
	return autoConvert_config_QoSPolicy_To_v1alpha1_QoSPolicy(in, out, s)
}

func autoConvert_v1alpha1_ReadWriteLimit_To_config_ReadWriteLimit(in *ReadWriteLimit, out *config.ReadWriteLimit, s conversion.Scope) error {
	out.ReadLimit = in.ReadLimit
	out.WriteLimit = in.WriteLimit
	return nil
}

// Convert_v1alpha1_ReadWriteLimit_To_config_ReadWriteLimit is an autogenerated conversion function.
func Convert_v1alpha1_ReadWriteLimit_To_config_ReadWriteLimit(in *ReadWriteLimit, out *config.ReadWriteLimit, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReadWriteLimit_To_config_ReadWriteLimit(in, out, s)
}

func autoConvert_config_ReadWriteLimit_To_v1alpha1_ReadWriteLimit(in *config.ReadWriteLimit, out *ReadWriteLimit, s conversion.Scope) error {
	out.ReadLimit = in.ReadLimit
	out.WriteLimit = in.WriteLimit
	return nil
}

// Convert_config_ReadWriteLimit_To_v1alpha1_ReadWriteLimit is an autogenerated conversion function.
func Convert_config_ReadWriteLimit_To_v1alpha1_ReadWriteLimit(in *config.ReadWriteLimit, out *ReadWriteLimit, s conversion.Scope) error {
	return autoConvert_config_ReadWriteLimit_To_v1alpha1_ReadWriteLimit(in, out, s)
}
