//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	duros "github.com/metal-stack/gardener-extension-duros/pkg/apis/duros"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DurosConfig)(nil), (*duros.DurosConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurosConfig_To_duros_DurosConfig(a.(*DurosConfig), b.(*duros.DurosConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*duros.DurosConfig)(nil), (*DurosConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_duros_DurosConfig_To_v1alpha1_DurosConfig(a.(*duros.DurosConfig), b.(*DurosConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DurosSeedStorageClass)(nil), (*duros.DurosSeedStorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurosSeedStorageClass_To_duros_DurosSeedStorageClass(a.(*DurosSeedStorageClass), b.(*duros.DurosSeedStorageClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*duros.DurosSeedStorageClass)(nil), (*DurosSeedStorageClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_duros_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(a.(*duros.DurosSeedStorageClass), b.(*DurosSeedStorageClass), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DurosConfig_To_duros_DurosConfig(in *DurosConfig, out *duros.DurosConfig, s conversion.Scope) error {
	out.ProjectID = in.ProjectID
	out.StorageClasses = *(*[]duros.DurosSeedStorageClass)(unsafe.Pointer(&in.StorageClasses))
	return nil
}

// Convert_v1alpha1_DurosConfig_To_duros_DurosConfig is an autogenerated conversion function.
func Convert_v1alpha1_DurosConfig_To_duros_DurosConfig(in *DurosConfig, out *duros.DurosConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurosConfig_To_duros_DurosConfig(in, out, s)
}

func autoConvert_duros_DurosConfig_To_v1alpha1_DurosConfig(in *duros.DurosConfig, out *DurosConfig, s conversion.Scope) error {
	out.ProjectID = in.ProjectID
	out.StorageClasses = *(*[]DurosSeedStorageClass)(unsafe.Pointer(&in.StorageClasses))
	return nil
}

// Convert_duros_DurosConfig_To_v1alpha1_DurosConfig is an autogenerated conversion function.
func Convert_duros_DurosConfig_To_v1alpha1_DurosConfig(in *duros.DurosConfig, out *DurosConfig, s conversion.Scope) error {
	return autoConvert_duros_DurosConfig_To_v1alpha1_DurosConfig(in, out, s)
}

func autoConvert_v1alpha1_DurosSeedStorageClass_To_duros_DurosSeedStorageClass(in *DurosSeedStorageClass, out *duros.DurosSeedStorageClass, s conversion.Scope) error {
	out.Name = in.Name
	out.ReplicaCount = in.ReplicaCount
	out.Compression = in.Compression
	out.Encryption = in.Encryption
	out.Default = in.Default
	out.QoS = in.QoS
	return nil
}

// Convert_v1alpha1_DurosSeedStorageClass_To_duros_DurosSeedStorageClass is an autogenerated conversion function.
func Convert_v1alpha1_DurosSeedStorageClass_To_duros_DurosSeedStorageClass(in *DurosSeedStorageClass, out *duros.DurosSeedStorageClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurosSeedStorageClass_To_duros_DurosSeedStorageClass(in, out, s)
}

func autoConvert_duros_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(in *duros.DurosSeedStorageClass, out *DurosSeedStorageClass, s conversion.Scope) error {
	out.Name = in.Name
	out.ReplicaCount = in.ReplicaCount
	out.Compression = in.Compression
	out.Encryption = in.Encryption
	out.Default = in.Default
	out.QoS = in.QoS
	return nil
}

// Convert_duros_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass is an autogenerated conversion function.
func Convert_duros_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(in *duros.DurosSeedStorageClass, out *DurosSeedStorageClass, s conversion.Scope) error {
	return autoConvert_duros_DurosSeedStorageClass_To_v1alpha1_DurosSeedStorageClass(in, out, s)
}
