//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2025 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	durosprovider "github.com/metal-stack/gardener-extension-duros-provider/pkg/apis/durosprovider"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DurosProviderConfig)(nil), (*durosprovider.DurosProviderConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurosProviderConfig_To_durosprovider_DurosProviderConfig(a.(*DurosProviderConfig), b.(*durosprovider.DurosProviderConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*durosprovider.DurosProviderConfig)(nil), (*DurosProviderConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_durosprovider_DurosProviderConfig_To_v1alpha1_DurosProviderConfig(a.(*durosprovider.DurosProviderConfig), b.(*DurosProviderConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DurosProviderConfig_To_durosprovider_DurosProviderConfig(in *DurosProviderConfig, out *durosprovider.DurosProviderConfig, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_DurosProviderConfig_To_durosprovider_DurosProviderConfig is an autogenerated conversion function.
func Convert_v1alpha1_DurosProviderConfig_To_durosprovider_DurosProviderConfig(in *DurosProviderConfig, out *durosprovider.DurosProviderConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurosProviderConfig_To_durosprovider_DurosProviderConfig(in, out, s)
}

func autoConvert_durosprovider_DurosProviderConfig_To_v1alpha1_DurosProviderConfig(in *durosprovider.DurosProviderConfig, out *DurosProviderConfig, s conversion.Scope) error {
	return nil
}

// Convert_durosprovider_DurosProviderConfig_To_v1alpha1_DurosProviderConfig is an autogenerated conversion function.
func Convert_durosprovider_DurosProviderConfig_To_v1alpha1_DurosProviderConfig(in *durosprovider.DurosProviderConfig, out *DurosProviderConfig, s conversion.Scope) error {
	return autoConvert_durosprovider_DurosProviderConfig_To_v1alpha1_DurosProviderConfig(in, out, s)
}
